### ISSUE TITLE
 打扰了，可否问下数据的来源，Sorry to bother you, could I know the source of dataset?

### ISSUE THREAD

**Issue by Tachy0nOwO** [sjtuhuoda/CV19#1]
你好，我找不到你的联系方式，只能在issue上问了qwq。我在github和kaggle上搜了policy里面的数据，都找不到来源，但是我的项目或许在后期会用到这些数据集，方便问一下policy里面的数据都是哪里找的吗？我需要给出link才能在项目里使用。

Hi，This is the only way to contact you, I am sorry to open such issue. I search for the dataset document policy, but I cannot find the source. I wonder if you can tell me the source website or institution of the dataset?

**Comment by sjtuhuoda** [comment]
你好。政策数据主要参考了牛津大学的一项研究 Thomas Hale, Sam Webster, Anna Petherick, Toby Phillips, and Beatriz Kira (2020). Oxford COVID-19 Government Response Tracker, Blavatnik School of Government。

**Comment by Tachy0nOwO** [comment]
谢谢你！！！！
